name: "CI"

on:
  pull_request:
  push:
    branches:
      - "master"

env:
  COMPOSER_ROOT_VERSION: "2.99.99"

jobs:

  unit-tests:
    name: "Unit Tests"
    runs-on: "ubuntu-latest"
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        php:
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          coverage: none
          tools: "composer:v2"
      - uses: "ramsey/composer-install@v1"
      - name: "Run unit tests"
        run: "./vendor/bin/phpunit --no-coverage"